version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Entered the install phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - java -version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - ACCOUNT_NUMBER=$(aws sts get-caller-identity --output text --query 'Account')
      - REPOSITORY_URI=$ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/wcmc/reciter/report
      - echo $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"reciter-report","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json